---
title: "Data Science Project - Loan Approval"
author: "Alex Biuckians, Armin Soroosh, Dania Salman, Kaipu Liu"
output:
  html_document:
    code_folding: hide
    number_sections: false
    theme: journal
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
library(ezids)
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, message = F)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```

## Loading the Dataset
```{r read_dataset, echo=TRUE}
# reading dataset
loan_df <- data.frame(read.csv("loan_approval_dataset.csv"))
```

```{r explore_dataset, echo=TRUE}
# exploring dataset
str(loan_df)
head(loan_df)
```

## Data Cleaning & Summary

### subsetting data and converting categorical variables to factor
```{r data_cleaning, echo=TRUE}
loan_df <- subset(loan_df, select = -c(loan_id))

# converting the numeric variables to factor variables
loan_df$no_of_dependents = as.factor(loan_df$no_of_dependents)
loan_df$education = as.factor(loan_df$education)
loan_df$self_employed = as.factor(loan_df$self_employed)
loan_df$loan_status = as.factor(loan_df$loan_status)
str(loan_df)
```
### Finding NA values
```{r, echo=TRUE}
sum(is.na(loan_df))
```
There are no NA values in the data set

### Summary of the dataset
```{r echo=TRUE}
summary(loan_df)
```
